version: '3.8'

services:
  api:
    container_name: api_service
    build: ./main-application
    volumes:
      - ./main-application:/main-application
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    restart: unless-stopped

  mongo:
    container_name: mongo_db
    image: mongo:6
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo-data: